/run/initialize
/vis/open OGL
/vis/viewer/set/viewpointVector -1 -0.3 0.5
/vis/geometry/set/colour logicWorld 1 116 204 244 0.1
#/vis/geometry/set/forceCloud logicWorld 1 1 5000
/vis/geometry/set/colour logicPhantom 1 0 188 216 0.2
/vis/geometry/set/forceSolid logicPhantom 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set gamma black
#/vis/modeling/trajectories/drawByParticleID-0/set neutron black
#/vis/modeling/trajectories/drawByParticleID-0/set proton black
#/vis/modeling/trajectories/drawByParticleID-0/set e+ black
#/vis/modeling/trajectories/drawByParticleID-0/set e- black
#/vis/modeling/trajectories/drawByParticleID-0/set pi+ black
#/vis/modeling/trajectories/drawByParticleID-0/set pi- black
#/vis/modeling/trajectories/drawByParticleID-0/set alpha black
#/vis/modeling/trajectories/drawByParticleID-0/set triton black
#/vis/modeling/trajectories/drawByParticleID-0/set deuteron black
#/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
